/* Auto-generated by genmsg_cpp for file /home/chad/cwrutemp/cwru_experimental/chad_sonar/msg/Sonar.msg */
#ifndef CHAD_SONAR_MESSAGE_SONAR_H
#define CHAD_SONAR_MESSAGE_SONAR_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"

#include "roslib/Header.h"

namespace chad_sonar
{
template <class ContainerAllocator>
struct Sonar_ : public ros::Message
{
  typedef Sonar_<ContainerAllocator> Type;

  Sonar_()
  : header()
  , range(0.0)
  , beam_angle(0.0)
  , max_range(0.0)
  , min_range(0.0)
  {
  }

  Sonar_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , range(0.0)
  , beam_angle(0.0)
  , max_range(0.0)
  , min_range(0.0)
  {
  }

  typedef  ::roslib::Header_<ContainerAllocator>  _header_type;
   ::roslib::Header_<ContainerAllocator>  header;

  typedef float _range_type;
  float range;

  typedef float _beam_angle_type;
  float beam_angle;

  typedef float _max_range_type;
  float max_range;

  typedef float _min_range_type;
  float min_range;


private:
  static const char* __s_getDataType_() { return "chad_sonar/Sonar"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROSCPP_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "0435d13783d80e0ae5cb4d54636c24aa"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROSCPP_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "# Message for the sonar scans\n\
Header header\n\
# Scan information\n\
float32 range # meters\n\
float32 beam_angle # rads\n\
float32 max_range # meters\n\
float32 min_range # meters\n\
\n\
================================================================================\n\
MSG: roslib/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROSCPP_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROSCPP_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, header);
    ros::serialization::serialize(stream, range);
    ros::serialization::serialize(stream, beam_angle);
    ros::serialization::serialize(stream, max_range);
    ros::serialization::serialize(stream, min_range);
    return stream.getData();
  }

  ROSCPP_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, header);
    ros::serialization::deserialize(stream, range);
    ros::serialization::deserialize(stream, beam_angle);
    ros::serialization::deserialize(stream, max_range);
    ros::serialization::deserialize(stream, min_range);
    return stream.getData();
  }

  ROSCPP_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(header);
    size += ros::serialization::serializationLength(range);
    size += ros::serialization::serializationLength(beam_angle);
    size += ros::serialization::serializationLength(max_range);
    size += ros::serialization::serializationLength(min_range);
    return size;
  }

  typedef boost::shared_ptr< ::chad_sonar::Sonar_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::chad_sonar::Sonar_<ContainerAllocator>  const> ConstPtr;
}; // struct Sonar
typedef  ::chad_sonar::Sonar_<std::allocator<void> > Sonar;

typedef boost::shared_ptr< ::chad_sonar::Sonar> SonarPtr;
typedef boost::shared_ptr< ::chad_sonar::Sonar const> SonarConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::chad_sonar::Sonar_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::chad_sonar::Sonar_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace chad_sonar

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::chad_sonar::Sonar_<ContainerAllocator> > {
  static const char* value() 
  {
    return "0435d13783d80e0ae5cb4d54636c24aa";
  }

  static const char* value(const  ::chad_sonar::Sonar_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x0435d13783d80e0aULL;
  static const uint64_t static_value2 = 0xe5cb4d54636c24aaULL;
};

template<class ContainerAllocator>
struct DataType< ::chad_sonar::Sonar_<ContainerAllocator> > {
  static const char* value() 
  {
    return "chad_sonar/Sonar";
  }

  static const char* value(const  ::chad_sonar::Sonar_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::chad_sonar::Sonar_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# Message for the sonar scans\n\
Header header\n\
# Scan information\n\
float32 range # meters\n\
float32 beam_angle # rads\n\
float32 max_range # meters\n\
float32 min_range # meters\n\
\n\
================================================================================\n\
MSG: roslib/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::chad_sonar::Sonar_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::chad_sonar::Sonar_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::chad_sonar::Sonar_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.range);
    stream.next(m.beam_angle);
    stream.next(m.max_range);
    stream.next(m.min_range);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Sonar_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::chad_sonar::Sonar_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::chad_sonar::Sonar_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::roslib::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "range: ";
    Printer<float>::stream(s, indent + "  ", v.range);
    s << indent << "beam_angle: ";
    Printer<float>::stream(s, indent + "  ", v.beam_angle);
    s << indent << "max_range: ";
    Printer<float>::stream(s, indent + "  ", v.max_range);
    s << indent << "min_range: ";
    Printer<float>::stream(s, indent + "  ", v.min_range);
  }
};


} // namespace message_operations
} // namespace ros

#endif // CHAD_SONAR_MESSAGE_SONAR_H

